name: CI (Go)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install gcc libsoxr-dev libasound2-dev libsamplerate-dev pkg-config -y

          go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9

      - name: Run tests
        run: go test -v ./...
